name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build project
        run: |
          cargo build --release
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gameserver-release-binary
          path: target/release/gameserver