name: Deploy

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: gameserver-release-binary
      - name: Upload binary via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: gameserver
          target: ${{ vars.DEPLOY_PATH }}
