name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      binary_path: ${{ steps.build.outputs.binary_path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build project
        id: build
        run: |
          cargo build --release
          echo "binary_path=$(realpath target/release/gameserver)" >> $GITHUB_ENV

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload binary via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: ${{ needs.build.outputs.binary_path }}
          target: "/var/www/gameserver"
